name: Daily Learning Update
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:     # 允許手動觸發

jobs:
  update-learning:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 添加寫入權限
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pyyaml gitpython markdown
      - name: Run tracker
        run: python leetcode_tracker.py
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Daily learning update" || echo "No changes to commit"
          git push
