name: Update Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'learning_notes/*.md'

jobs:
  update-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List directory contents
        run: |
          pwd
          ls -la
          ls -la learning_notes/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Run solution updater
        run: |
          python -c "import os; print(os.getcwd()); print(os.listdir())"
          python solution_updater.py

      - name: Check for changes
        run: |
          git status
          ls -la learning_notes/

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add learning_notes/*.md
          git commit -m "Update solution analysis" || echo "No changes to commit"
          git push
